version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data/
  api:
    container_name: api
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      DEVISE_JWT_SECRET_KEY: 0Fbrnc09eYEBqFOOZHeD5to1dnyjpU3nVXHH4CRQ
  client:
    container_name: client
    build: ./client
    command: yarn run dev -p 3333
    volumes:
      - ./client:/client
    ports:
      - "3333:3333"
    # depends_on:
    #   - back
volumes:
  postgresdb:
